export const registerUser = (data) => api.post("/register", data)
export const loginUser = (data) => api.post("/login", data)
export const forgotPassword = (data) => api.post("/forgot-password", data)
export const resetPassword = (token, data) => api.post("/reset-password", {token, password: data.password})
// export const login = (data) => api.post("/login", data)