ALTER TABLE users
    ADD bio VARCHAR(255) NULL;

ALTER TABLE users
    ADD phone VARCHAR(255) NULL;

ALTER TABLE users
    ADD profile_image VARCHAR(255) NULL;

ALTER TABLE users
    ADD COLUMN lock_time TIMESTAMP NULL;